
management:
  tracing:
    sampling:
      probability: 1.0
spring.datasource:
  url: jdbc:postgresql://34.126.185.203:5544/mini_pro_db
  username: postgres
  password: 1234
spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/euraka/
spring:
  application:
    name: task-service
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.sythorng.site/auth/realms/SpringMiniProject
          jwk-set-uri: https://keycloak.sythorng.site/auth/realms/SpringMiniProject/protocol/openid-connect/certs

keycloak:
  realm: SpringMiniProject
  resource: mini-project-app
  #  auth-server-url: https://demo.docengine.tech/auth/ #docker container
  auth-server-url: https://keycloak.sythorng.site/auth/ #docker container
  credentials:
    username: 'admin'
    password: 'admin'
    client-id: 'mini-project-app' # admin account for creating users
    secret: 'atLclipZd1OTTVCg70XJRhkZezfmTIVe'
    provider: secret
server:
  port: 8082

openapi:
  service:
    title: task-service
    version: 1.0.0
    url: http://localhost:8082
springdoc:
  api-docs:
    path: /task-service/v3/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html


keycloak.Url : http://localhost:8081/api/v1
